# Type Name             ID  Description                                  Home                       Shell
u      hepta-browserd    -   "TrillionniumOS Desktop browser service"    /var/lib/hepta-browserd    /usr/sbin/nologin
u      hepta-agent       -   "TrillionniumOS Desktop Agent client"       /var/lib/hepta-agent       /usr/sbin/nologin
