# Type Name             ID  GECOS                                      Home                       Shell
g      hepta-agent      -
g      hepta-agent-socket -
u      hepta-agent      -   "Trillionnium Desktop local Agent principal" /nonexistent               /usr/sbin/nologin
u      hepta-browserd   -   "Trillionnium Desktop browser mechanism"   /var/lib/hepta-browserd   /usr/sbin/nologin
m      hepta-browserd   hepta-agent
m      hepta-agent      hepta-agent-socket
