# Type Path                         Mode User            Group                Age Argument
d      /run/hepta                   0755 root            root                 -   -
d      /run/hepta/browserd          0750 root            hepta-agent-socket   -   -
d      /var/lib/hepta-browserd      0700 hepta-browserd  hepta-browserd       -   -
