[Service]
Environment=HOME=/run/hepta-desktop
Environment=XDG_CACHE_HOME=/run/hepta-desktop/cache
Environment=XDG_CONFIG_HOME=/run/hepta-desktop/config
ExecStartPre=/usr/bin/mkdir -p /run/hepta-desktop/cache /run/hepta-desktop/config
StandardOutput=journal+console
StandardError=journal+console
