//! Real-filesystem managed-head tests; no browser, network or external effects.
use hepta_session_core::{
    JournalError, JournalId, JournalOpenPolicy, ManagedOpenPolicy as Policy, ReceiptJournal,
    ReceiptLifecycleState as State,
};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::os::unix::fs::{PermissionsExt, symlink};
use std::path::Path;
#[allow(dead_code)]
#[path = "support/journal_chain_fixture.rs"]
mod fixture;
use fixture::*;

fn complete(writer: &mut ReceiptJournal, id: &str) {
    writer.append(event(id, State::Requested)).unwrap();
    writer.append(event(id, State::Interrupted)).unwrap();
}
fn open(root: &Path) -> ReceiptJournal {
    ReceiptJournal::open_managed(root, ID, Policy::STRICT).unwrap()
}
fn segments(root: &Path, n: usize) -> std::path::PathBuf {
    root.join(format!("segment-{n:016}.journal"))
}
fn two(root: &Path) {
    let mut writer = ReceiptJournal::create_managed(root, ID, 1).unwrap();
    complete(&mut writer, "first");
    let (_, mut next) = writer.rotate_managed(2).unwrap();
    complete(&mut next, "second");
}
fn prepared(root: &Path) {
    let mut writer = ReceiptJournal::create_managed(root, ID, 1).unwrap();
    complete(&mut writer, "first");
    let (_, next) = writer.rotate_managed(2).unwrap();
    drop(next);
    // Construct the precise durable pre-publication state using a real linked
    // header generated by rotate, without inserting faults in the product.
    fs::rename(segments(root, 2), root.join("next.pending")).unwrap();
}

#[test]
fn managed_reopen_selects_latest_head_and_all_receipt_ids() {
    let temp = Temp::new();
    let root = temp.path("store");
    two(&root);
    let mut writer = open(&root);
    assert!(writer.is_managed());
    assert_eq!(writer.path(), segments(&root, 2));
    let before = fs::read(writer.path()).unwrap();
    for id in ["first", "second"] {
        assert!(writer.append(event(id, State::Requested)).is_err());
    }
    assert_eq!(fs::read(writer.path()).unwrap(), before);
    assert_eq!(
        writer
            .append(event("third", State::Requested))
            .unwrap()
            .sequence,
        5
    );
}
#[test]
fn managed_store_cannot_downgrade_to_any_unmanaged_writer_api() {
    let temp = Temp::new();
    let root = temp.path("store");
    two(&root);
    let first = segments(&root, 1);
    let last = segments(&root, 2);
    assert!(ReceiptJournal::open(&first, JournalOpenPolicy::RECOVER_CRASH).is_err());
    assert!(ReceiptJournal::open_chain([&first], ID, JournalOpenPolicy::STRICT).is_err());
    assert!(ReceiptJournal::open_chain([&first, &last], ID, JournalOpenPolicy::STRICT).is_err());
    assert!(ReceiptJournal::create(root.join("new"), ID, 1).is_err());
    let writer = open(&root);
    assert!(writer.rotate(root.join("new"), 3).is_err());
    assert!(!root.join("new").exists());
    assert_eq!(fs::read_dir(&root).unwrap().count(), 3);
}
#[test]
fn pending_header_requires_explicit_recovery_and_preserves_chain() {
    let temp = Temp::new();
    let root = temp.path("store");
    prepared(&root);
    let before = fs::read(segments(&root, 1)).unwrap();
    let pending = fs::read(root.join("next.pending")).unwrap();
    assert!(ReceiptJournal::open_managed(&root, ID, Policy::STRICT).is_err());
    assert_eq!(fs::read(root.join("next.pending")).unwrap(), pending);
    let mut writer = ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).unwrap();
    assert_eq!(writer.path(), segments(&root, 2));
    assert!(!root.join("next.pending").exists());
    assert_eq!(fs::read(segments(&root, 2)).unwrap(), pending);
    assert_eq!(fs::read(segments(&root, 1)).unwrap(), before);
    assert!(writer.append(event("first", State::Requested)).is_err());
    assert_eq!(
        writer
            .append(event("new", State::Requested))
            .unwrap()
            .sequence,
        3
    );
}
#[test]
fn prepared_first_header_can_complete_interrupted_initial_publication() {
    let temp = Temp::new();
    let root = temp.path("store");
    drop(ReceiptJournal::create_managed(&root, ID, 1).unwrap());
    fs::rename(segments(&root, 1), root.join("next.pending")).unwrap();
    let mut writer = ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).unwrap();
    assert_eq!(
        writer
            .append(event("one", State::Requested))
            .unwrap()
            .sequence,
        1
    );
}
#[test]
fn pending_with_receipt_records_is_not_a_prepared_rotation() {
    let temp = Temp::new();
    let root = temp.path("store");
    two(&root);
    fs::rename(segments(&root, 2), root.join("next.pending")).unwrap();
    let before = fs::read(root.join("next.pending")).unwrap();
    assert!(ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).is_err());
    assert_eq!(fs::read(root.join("next.pending")).unwrap(), before);
    assert!(!segments(&root, 2).exists());
}
#[test]
fn malformed_pending_is_never_discarded_or_truncated() {
    for bytes in [b"".as_slice(), b"HPTJRNL1", b"invalid full header"] {
        let temp = Temp::new();
        let root = temp.path("store");
        prepared(&root);
        fs::write(root.join("next.pending"), bytes).unwrap();
        let prior = fs::read(segments(&root, 1)).unwrap();
        assert!(ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).is_err());
        assert_eq!(fs::read(root.join("next.pending")).unwrap(), bytes);
        assert_eq!(fs::read(segments(&root, 1)).unwrap(), prior);
    }
}
#[test]
fn wrong_journal_id_is_rejected_before_pending_publication() {
    let temp = Temp::new();
    let root = temp.path("store");
    prepared(&root);
    let before = fs::read(root.join("next.pending")).unwrap();
    assert!(
        ReceiptJournal::open_managed(&root, JournalId([7; 16]), Policy::RECOVER_CRASH).is_err()
    );
    assert_eq!(fs::read(root.join("next.pending")).unwrap(), before);
}
#[test]
fn pending_cannot_authorize_repair_of_a_committed_predecessor() {
    let temp = Temp::new();
    let root = temp.path("store");
    prepared(&root);
    OpenOptions::new()
        .append(true)
        .open(segments(&root, 1))
        .unwrap()
        .write_all(b"HPTREC01")
        .unwrap();
    let before = fs::read(segments(&root, 1)).unwrap();
    assert!(ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).is_err());
    assert_eq!(fs::read(segments(&root, 1)).unwrap(), before);
    assert!(!segments(&root, 2).exists());
}
#[test]
fn active_torn_tail_is_repaired_only_after_complete_managed_selection() {
    let temp = Temp::new();
    let root = temp.path("store");
    two(&root);
    let before = fs::read(segments(&root, 2)).unwrap();
    OpenOptions::new()
        .append(true)
        .open(segments(&root, 2))
        .unwrap()
        .write_all(b"HPTREC01")
        .unwrap();
    assert!(ReceiptJournal::open_managed(&root, ID, Policy::STRICT).is_err());
    let mut writer = ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).unwrap();
    assert_eq!(fs::read(segments(&root, 2)).unwrap(), before);
    assert!(writer.append(event("first", State::Requested)).is_err());
}
#[test]
fn inventory_rejects_gaps_unknown_files_and_noncanonical_names() {
    for alteration in ["gap", "extra", "name"] {
        let temp = Temp::new();
        let root = temp.path("store");
        two(&root);
        match alteration {
            "gap" => {
                fs::remove_file(segments(&root, 1)).unwrap();
            }
            "extra" => {
                fs::write(root.join("ignored.txt"), b"no").unwrap();
                fs::set_permissions(root.join("ignored.txt"), fs::Permissions::from_mode(0o600))
                    .unwrap();
            }
            _ => {
                fs::rename(segments(&root, 2), root.join("segment-2.journal")).unwrap();
            }
        }
        assert!(ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).is_err());
    }
}
#[test]
fn store_rejects_symlinks_hardlink_aliases_and_permission_drift() {
    for kind in ["root", "marker", "segment", "hardlink", "permissions"] {
        let temp = Temp::new();
        let root = temp.path("store");
        two(&root);
        match kind {
            "root" => {
                fs::rename(&root, temp.path("real")).unwrap();
                symlink(temp.path("real"), &root).unwrap();
            }
            "marker" => {
                fs::rename(root.join("store.v1"), temp.path("marker")).unwrap();
                symlink(temp.path("marker"), root.join("store.v1")).unwrap();
            }
            "segment" => {
                fs::rename(segments(&root, 2), temp.path("seg")).unwrap();
                symlink(temp.path("seg"), segments(&root, 2)).unwrap();
            }
            "hardlink" => {
                fs::hard_link(segments(&root, 1), temp.path("alias")).unwrap();
            }
            _ => {
                fs::set_permissions(&root, fs::Permissions::from_mode(0o750)).unwrap();
            }
        }
        assert!(ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).is_err());
    }
}
#[test]
fn marker_replacement_or_inplace_mutation_poison_the_live_writer() {
    for replacement in [false, true] {
        let temp = Temp::new();
        let root = temp.path("store");
        let mut writer = ReceiptJournal::create_managed(&root, ID, 1).unwrap();
        let before = fs::read(writer.path()).unwrap();
        let marker = root.join("store.v1");
        let mut bytes = fs::read(&marker).unwrap();
        if replacement {
            fs::remove_file(&marker).unwrap();
        } else {
            bytes[8] ^= 1;
        }
        fs::write(&marker, bytes).unwrap();
        fs::set_permissions(&marker, fs::Permissions::from_mode(0o600)).unwrap();
        assert!(writer.append(event("one", State::Requested)).is_err());
        assert!(matches!(
            writer.append(event("two", State::Requested)),
            Err(JournalError::WriterPoisoned)
        ));
        assert_eq!(fs::read(writer.path()).unwrap(), before);
    }
}
#[test]
fn concurrent_managed_open_cannot_acquire_second_writer() {
    let temp = Temp::new();
    let root = temp.path("store");
    let writer = ReceiptJournal::create_managed(&root, ID, 1).unwrap();
    assert!(matches!(
        ReceiptJournal::open_managed(&root, ID, Policy::STRICT),
        Err(JournalError::WriterBusy)
    ));
    drop(writer);
    drop(open(&root));
}
#[test]
fn unresolved_receipt_blocks_rotation_without_publishing_pending() {
    let temp = Temp::new();
    let root = temp.path("store");
    let mut writer = ReceiptJournal::create_managed(&root, ID, 1).unwrap();
    writer.append(event("one", State::Requested)).unwrap();
    let before = fs::read(writer.path()).unwrap();
    assert!(writer.rotate_managed(2).is_err());
    assert!(!root.join("next.pending").exists());
    assert_eq!(fs::read(segments(&root, 1)).unwrap(), before);
    assert_eq!(open(&root).inspect().unwrap().unresolved.len(), 1);
}
#[test]
fn repeated_rotation_has_a_bounded_nonpruning_namespace() {
    let temp = Temp::new();
    let root = temp.path("store");
    let mut writer = ReceiptJournal::create_managed(&root, ID, 1).unwrap();
    complete(&mut writer, "one");
    for n in 2..=64 {
        writer = writer.rotate_managed(n).unwrap().1;
    }
    assert!(writer.rotate_managed(65).is_err());
    assert!(!root.join("next.pending").exists());
    let mut writer = open(&root);
    assert!(writer.append(event("one", State::Requested)).is_err());
    assert_eq!(fs::read_dir(&root).unwrap().count(), 65);
}
#[test]
fn creation_rejects_existing_directories_and_bad_paths_without_files() {
    let temp = Temp::new();
    let root = temp.path("store");
    fs::create_dir(&root).unwrap();
    assert!(ReceiptJournal::create_managed(&root, ID, 1).is_err());
    assert_eq!(fs::read_dir(&root).unwrap().count(), 0);
    for path in [
        temp.path("bad name"),
        temp.path("bad\nname"),
        temp.path("x/../bad"),
    ] {
        assert!(ReceiptJournal::create_managed(&path, ID, 1).is_err());
        assert!(!path.exists());
    }
}
#[test]
fn changed_root_or_added_pending_stops_inspection_and_sealing() {
    for rotate_root in [true, false] {
        let temp = Temp::new();
        let root = temp.path("store");
        let mut writer = ReceiptJournal::create_managed(&root, ID, 1).unwrap();
        if rotate_root {
            fs::rename(&root, temp.path("moved")).unwrap();
            fs::create_dir(&root).unwrap();
        } else {
            fs::write(root.join("next.pending"), b"unexpected").unwrap();
        }
        assert!(writer.inspect().is_err());
        assert!(matches!(writer.seal(), Err(JournalError::WriterPoisoned)));
    }
}

#[test]
fn automatic_rotation_trigger_waits_for_terminal_facts_and_resets_after_commit() {
    let temp = Temp::new();
    let root = temp.path("store");
    let mut writer = ReceiptJournal::create_managed(&root, ID, 1).unwrap();
    assert!(!writer.managed_rotation_due());
    let mut count = 0;
    while !writer.managed_rotation_due() {
        count += 1;
        assert!(count < 2000);
        for state in [State::Requested, State::Interrupted] {
            let mut value = event(&format!("size-{count}"), state);
            value.detail = Some("x".repeat(4096));
            writer.append(value).unwrap();
        }
    }
    writer.append(event("inflight", State::Requested)).unwrap();
    assert!(!writer.managed_rotation_due());
    writer
        .append(event("inflight", State::Interrupted))
        .unwrap();
    assert!(writer.managed_rotation_due());
    let (_, mut writer) = writer.rotate_managed(3).unwrap();
    assert!(!writer.managed_rotation_due());
    assert!(writer.append(event("size-1", State::Requested)).is_err());
}
#[test]
fn prepared_header_with_wrong_predecessor_is_preserved_and_rejected() {
    let temp = Temp::new();
    let root = temp.path("store");
    prepared(&root);
    let other = temp.path("other");
    let mut writer = ReceiptJournal::create_managed(&other, ID, 1).unwrap();
    complete(&mut writer, "different");
    let (_, next) = writer.rotate_managed(3).unwrap();
    drop(next);
    let foreign = fs::read(segments(&other, 2)).unwrap();
    fs::write(root.join("next.pending"), &foreign).unwrap();
    assert!(ReceiptJournal::open_managed(&root, ID, Policy::RECOVER_CRASH).is_err());
    assert_eq!(fs::read(root.join("next.pending")).unwrap(), foreign);
    assert!(!segments(&root, 2).exists());
}
