#!/usr/bin/env python3
"""Deterministically project the Cargo module index; never promote a claim.

The existing module-documentation validator remains authoritative for detailed
README, API, feature, binary and reference checks. This adds the missing index
projection check, not a replacement for that validator.
"""
from __future__ import annotations

import argparse
import json
import re
import stat
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = "manifests/modules.v1.json"
INDEX = "docs/modules/README.md"
LIMIT = 1_048_576
IDENTIFIER = re.compile(r"[a-z][a-z0-9_-]*\Z")
MODULE_PATH = re.compile(r"(?:apps|crates)/[a-z][a-z0-9-]*\Z")
HEADER = """<!-- Generated by tools/render_module_index.py; do not edit by hand. -->
# Module development documentation

This index is a deterministic projection of `manifests/modules.v1.json`, checked
against the exact Cargo workspace. It covers Cargo packages, not every product
subsystem. Package READMEs and the registry contain the matching claim ceilings;
no candidate status in this table establishes an integrated or released product.

Machine project truth, non-claims and exact-object evidence retain precedence.
The module-documentation validator separately checks the detailed per-package
contracts, references, binary inventory and feature inventory.

## Coverage

| Module and technical contract | Workspace path | Source status |
| --- | --- | --- |
"""
FOOTER = """
## Change workflow

Update implementation, Cargo metadata, module README and module registry together.
Regenerate this index with `python3 tools/render_module_index.py > docs/modules/README.md`.
Run `python3 tools/render_module_index.py --check`, the module-documentation gate,
and its hostile tests. The index check rejects stale, missing or additional rows;
it never changes project truth or treats source presence as runtime qualification.

Exact-head and current prospective-merge qualification, independent review,
protected promotion and the required exact-main rerun remain separate obligations.
"""


def read_regular(root: Path, relative: str) -> str:
    """Reject symlink traversal and bound repository-document reads."""
    parts = relative.split("/")
    if root.is_symlink() or not root.is_dir():
        raise ValueError("repository root must be a real directory")
    if relative.startswith("/") or any(p in {"", ".", ".."} for p in parts):
        raise ValueError("noncanonical repository path")
    current = root
    for index, part in enumerate(parts):
        current /= part
        mode = current.lstat().st_mode
        if stat.S_ISLNK(mode):
            raise ValueError(f"symlink is forbidden: {relative}")
        if index < len(parts) - 1 and not stat.S_ISDIR(mode):
            raise ValueError(f"non-directory parent: {relative}")
    if not stat.S_ISREG(current.stat().st_mode):
        raise ValueError(f"not a regular file: {relative}")
    with current.open("rb") as stream:
        raw = stream.read(LIMIT + 1)
    if len(raw) > LIMIT:
        raise ValueError(f"document exceeds byte ceiling: {relative}")
    return raw.decode("utf-8")


def unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON member: {key}")
        result[key] = value
    return result


def reject_number(value: str) -> None:
    raise ValueError(f"non-integer JSON number: {value}")


def render(root: Path = ROOT) -> str:
    registry = json.loads(read_regular(root, REGISTRY), object_pairs_hook=unique_object,
                          parse_constant=reject_number, parse_float=reject_number)
    if not isinstance(registry, dict) or set(registry) != {"schema", "plan_revision", "policy", "modules"}:
        raise ValueError("invalid closed module registry envelope")
    if registry["schema"] != "trillionnium.desktop.modules.v1":
        raise ValueError("unsupported module registry version")
    cargo = tomllib.loads(read_regular(root, "Cargo.toml"))
    members = cargo.get("workspace", {}).get("members")
    modules = registry["modules"]
    if not isinstance(modules, list) or not modules:
        raise ValueError("module registry must be nonempty")
    if not isinstance(members, list) or len(members) != len(modules):
        raise ValueError("workspace and registry differ")
    paths: list[str] = []
    ids: set[str] = set()
    rows: list[str] = []
    for entry in modules:
        if not isinstance(entry, dict):
            raise ValueError("invalid module entry")
        name, path, status = (entry.get(k) for k in ("id", "path", "status"))
        if not isinstance(name, str) or not IDENTIFIER.fullmatch(name) or name in ids:
            raise ValueError("invalid or duplicated module identifier")
        if not isinstance(path, str) or not MODULE_PATH.fullmatch(path):
            raise ValueError("invalid module path")
        if not isinstance(status, str) or not IDENTIFIER.fullmatch(status):
            raise ValueError("invalid module status")
        if entry.get("package") != name or path.split("/")[-1] != name:
            raise ValueError("module/package/path identity mismatch")
        if entry.get("documentation") != f"{path}/README.md":
            raise ValueError("module documentation path mismatch")
        package = tomllib.loads(read_regular(root, f"{path}/Cargo.toml")).get("package", {})
        if package.get("name") != name:
            raise ValueError("Cargo package identity mismatch")
        read_regular(root, entry["documentation"])
        ids.add(name)
        paths.append(path)
        rows.append(f"| [`{name}`](../../{path}/README.md) | `{path}` | `{status}` |\n")
    if paths != members or len(set(paths)) != len(paths):
        raise ValueError("workspace/registry paths or order differ")
    return HEADER + "".join(rows) + FOOTER


def validate(root: Path = ROOT) -> list[str]:
    try:
        expected = render(root)
        if read_regular(root, INDEX) != expected:
            return ["module index is stale; regenerate with tools/render_module_index.py"]
        return []
    except (OSError, ValueError, TypeError, KeyError) as error:
        return [f"module index validation failed: {error}"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check without modifying tracked files")
    args = parser.parse_args()
    if args.check:
        errors = validate()
        if errors:
            print("\n".join(errors), file=sys.stderr)
            return 1
        print("module index projection passed")
        return 0
    try:
        sys.stdout.write(render())
        return 0
    except (OSError, ValueError, TypeError, KeyError) as error:
        print(f"module index generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
