"""Linux mechanism adapters for the bounded S09 host-integration gate."""

from .adapters import (
    AtomicFileStore,
    AtomicWriteReceipt,
    DeadlineExpired,
    HttpsTarget,
    IdentityRefused,
    MonotonicClock,
    NetworkRefused,
    OsEntropy,
    PathRefused,
    PlatformError,
    ProcessIdentity,
    WaylandPeer,
    bind_connected_peer,
    connect_wayland_endpoint,
    globally_routable,
    read_bounded_regular_file,
    read_process_identity,
    validate_external_https,
    validate_redirect_chain,
)

__all__ = [
    "AtomicFileStore",
    "AtomicWriteReceipt",
    "DeadlineExpired",
    "HttpsTarget",
    "IdentityRefused",
    "MonotonicClock",
    "NetworkRefused",
    "OsEntropy",
    "PathRefused",
    "PlatformError",
    "ProcessIdentity",
    "WaylandPeer",
    "bind_connected_peer",
    "connect_wayland_endpoint",
    "globally_routable",
    "read_bounded_regular_file",
    "read_process_identity",
    "validate_external_https",
    "validate_redirect_chain",
]
